#!/usr/bin/env python3
"""Generate docs for transforms and framework backend contracts."""

from __future__ import annotations

from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from transforms.catalog import catalog_framework_interface
from transforms.catalog import catalog_transforms
from tools.runtime import SUPPORTED_FRAMEWORKS

DOCS_DIR = ROOT / "docs"
TRANSFORMS_DOC = DOCS_DIR / "transforms.md"
FRAMEWORKS_DOC = DOCS_DIR / "frameworks.md"


def render_transforms_md() -> str:
    transforms = list(catalog_transforms())
    lines: list[str] = []
    lines.append("# Transforms Reference")
    lines.append("")
    lines.append("This file is generated by `python tools/generate_catalog_docs.py`. Do not edit by hand.")
    lines.append("")
    lines.append(f"Total transforms: `{len(transforms)}`")
    lines.append("")
    lines.append("| Key | Title | Complexity | Formula | Description |")
    lines.append("|---|---|---:|---|---|")
    for t in transforms:
        key = str(t["key"])
        title = str(t["title"])
        complexity = int(t["complexity"])
        formula = str(t["formula"]).replace("|", "\\|")
        description = str(t["description"]).replace("|", "\\|")
        lines.append(f"| `{key}` | {title} | {complexity} | `{formula}` | {description} |")

    lines.append("")
    lines.append("## Presets")
    lines.append("")
    lines.append("| Key | samples | freq | amplitude | damping | noise | phase | grid |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    for t in transforms:
        p = t["preset"]
        lines.append(
            "| `{}` | {} | {} | {} | {} | {} | {} | {} |".format(
                t["key"],
                int(p["samples"]),
                float(p["freq"]),
                float(p["amplitude"]),
                float(p["damping"]),
                float(p["noise"]),
                float(p["phase"]),
                int(p["grid"]),
            )
        )

    lines.append("")
    return "\n".join(lines)


def render_frameworks_md() -> str:
    contract = catalog_framework_interface()
    lines: list[str] = []
    lines.append("# Frameworks Reference")
    lines.append("")
    lines.append("This file is generated by `python tools/generate_catalog_docs.py`. Do not edit by hand.")
    lines.append("")
    lines.append("## Supported Frameworks")
    lines.append("")
    for fw in SUPPORTED_FRAMEWORKS:
        lines.append(f"- `{fw}`")
    lines.append("")
    lines.append("## Engine Interface Contract")
    lines.append("")
    lines.append("Backends must expose the following in `frameworks/<framework>/utils.py`:")
    lines.append("")
    for name in contract["utils_entrypoints"]:
        lines.append(f"- `{name}`")
    lines.append("")
    lines.append("Engine ops adapter methods required for transform execution:")
    lines.append("")
    for name in contract["ops_adapter"]:
        lines.append(f"- `{name}`")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    TRANSFORMS_DOC.write_text(render_transforms_md(), encoding="utf-8")
    FRAMEWORKS_DOC.write_text(render_frameworks_md(), encoding="utf-8")
    print(f"Generated {TRANSFORMS_DOC.relative_to(ROOT)}")
    print(f"Generated {FRAMEWORKS_DOC.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
